### ISSUE TITLE
BBjTapiClient.exe window is unreachable out of scope

### ISSUE THREAD

**Issue by RVDHOFADP** [BasisHub/BBjTAPI#2]
Used it the first time with a second Monitor connected.
Later - during usage of Laptop alone - window was no longer available.
Next day - use with second Monitor again - still gone - no way

The window is opened anywhere out of scope and not visible as a tray Icon in that state.
watch example : http://screencast.com/t/wNiK7ivh

**Comment by StephanWald** [comment]
added some code to always center the window and raise it topmost
